### ISSUE TITLE
2.0.2 and 2.0.3 produce garbled output when used with postcss-custom-selectors

### ISSUE THREAD

**Issue by rgrove** [postcss/postcss-selector-matches#10]
PR #8, which was released in 2.0.2, seems to break [postcss-custom-selectors](https://github.com/postcss/postcss-custom-selectors/).

Here's a simple repro:
## Input

``` css
@custom-selector :--link a, a:active, a:visited;

:--link.foo,
.foo {
  color: green;
}
```
## Expected Output

This is what you get with postcss-selector-matches <= 2.0.1.

``` css
a.foo,
a:active.foo,
a:visited.foo,
.foo {
  color: green;
}
```
## Actual Output

This is what you get starting with postcss-selector-matches 2.0.2. Note the garbled `o.fo` classname.

``` css
a.foo,
a:active.foo,
a:visited.foo,
o.fo {
  color: green;
}
```

**Comment by TehShrike** [comment]
As of 2.0.2, the "should works with weird identifiers" test in postcss-custom-selectors started failing: https://github.com/postcss/postcss-custom-selectors/blob/cf0f7dcb82797f3d3475efd431b48ff273abbec2/test/index.js#L169-L195

**Comment by MoOx** [comment]
@yordis can you take a look to this?

**Comment by MoOx** [comment]
Should be fixed in 2.0.4. The change in 2.0.2 was really dangerous.

**Comment by rgrove** [comment]
@MoOx Thanks!

**Comment by rgrove** [comment]
Looks like 2.0.4 didn't quite fix everything. I've simplified the test case from this issue's description and added it as a failing unit test in PR #12.
